{
    'name': 'Enterprise Equipment Management',
    'version': '19.0.0.1.0',
    'category': 'Enterprise Equipment Management',
    'sequence': -100,
    'summary': 'Manage enterprise equipment, assignments, categories and history',
    'description': 'Enterprise Equipment Management - Track equipment items, assign them to employees, manage categories, and view full audit history.',
    'author': 'Wail Sari Bey',
    'website': 'https://www.wailsb.com',
    'depends': ['base', 'hr'],
    'data': [
        'security/equipment_security.xml',
        'security/ir.model.access.csv',
        'views/wizard_views.xml',
        'views/category_views.xml',
        'views/equipment_views.xml',
        'views/assignment_views.xml',
        'views/log_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
